services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmtest
      - POSTGRES_DB=mattermost
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mmuser -d mattermost"]
      interval: 5s
      timeout: 5s
      retries: 30

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmtest@postgres:5432/mattermost?sslmode=disable
      - MM_SQLSETTINGS_CONNECTION_MAX_IDLE_TIME=30000
      - MM_SERVICESETTINGS_ALLOWEDUNTRUSTEDINTERNALCONNECTIONS=poll-bot
      - MM_SERVICESETTINGS_ENABLECOMMANDS=true
    ports:
      - "8065:8065"
    volumes:
      - mattermost_data:/mattermost/data

volumes:
  mattermost_data:
  postgres_data: