services:
  poll-bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    depends_on:
      - tarantool
    environment:
      - TARANTOOL_HOST=tarantool
      - TARANTOOL_PORT=3301
      - TARANTOOL_PASS=testpass
      - MATTERMOST_TOKEN=${MATTERMOST_TOKEN}
      - MATTERMOST_WEBHOOK_SECRET=${MATTERMOST_WEBHOOK_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

  tarantool:
    image: tarantool/tarantool:latest
    volumes:
      - ./docker/tarantool/init.lua:/opt/tarantool/init.lua
      - tarantool_data:/var/lib/tarantool
    ports:
      - "3301:3301"
    healthcheck:
      test: [ "CMD", "tarantool", "-e", "require('tarantool').ping()" ]
      interval: 5s
      timeout: 3s
      retries: 5
    command: tarantool /opt/tarantool/init.lua

volumes:
  tarantool_data: